# Generated by Django 5.2 on 2025-05-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='watu',
        ),
    ]
